# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db_notifications:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  rabbitmq:
    image: rabbitmq:3.7-alpine
    # environment:
    #   - RABBITMQ_DEFAULT_USER=guest
    #   - RABBITMQ_DEFAULT_PASS=guest

  notifications:
    image: openzaak/open-notificaties
    environment: &notifications-env
      - DJANGO_SETTINGS_MODULE=nrc.conf.docker
      - SECRET_KEY=${SECRET_KEY:-y8=ynp!*&3z6!0ujpg$$0nry%j#1z2@%hq9+1doh1bl+86w)730}
      - DB_HOST=db_notifications
      - IS_HTTPS=no
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=redis:6379/1
      - CACHE_AXES=redis:6379/1
      - RABBITMQ_HOST=rabbitmq
      - PUBLISH_BROKER_URL=amqp://guest:guest@rabbitmq:5672/%2F
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - CELERY_LOGLEVEL=DEBUG
      - CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-2}
      - DEBUG=yes
    volumes:
      - ./fixtures_notificaties:/app/fixtures
    ports:
      - 8001:8000
    depends_on:
      - db_notifications
      - rabbitmq
      - redis

  celery:
    image: openzaak/open-notificaties
    environment: *notifications-env
    command: /celery_worker.sh
    depends_on:
      - db_notifications
      - rabbitmq
      - redis

  db:
    image: mdillon/postgis
    ports:
      - "5432"
    # environment:
    #   - POSTGRES_USER=${PG_USER:zrc}
    #   - POSTGRES_PASSWORD=${PG_PASSWORD:zrc}

  redis:
    image: redis

  mock-endpoints.local:
    image: nginx:1.19
    volumes:
      - ./docker/nginx/mocks.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certs:/certs:ro
    ports:
      - 9000:80
      - 9001:443

  celery-openzaak:
    build: .
    environment: &openzaak-env
      - DJANGO_SETTINGS_MODULE=openzaak.conf.docker
      - SECRET_KEY=${SECRET_KEY:-7(h1r2hk)8z9+05edulo_3qzymwbo&c24=)qz7+_@3&2sp=u%i}
      - IS_HTTPS=no
      - ALLOWED_HOSTS=localhost,web
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
      - SENDFILE_BACKEND=django_sendfile.backends.simple
      - DEBUG=yes
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - CELERY_LOGLEVEL=DEBUG
      - CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-4}
    command: /celery_worker.sh
    volumes:
      - ./fixtures:/app/fixtures
    depends_on:
      - db
      - rabbitmq
      - redis

  web:
    build: .
    environment: *openzaak-env
    volumes:
      - ./fixtures:/app/fixtures
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
      - redis
